Separate GetDenominationFrequencies
nopara73/Sake pull request #14
Opened 2023-02-28 09:59 UTC by molnard

2023-03-01 09:11 UTC, nopara73 requested changes
I think this prevents creating statistics from hundreds of rounds. It makes Sake slow and therefore unusable when you want to do statistically significant measurements, rather than just to get a hunch on your quick changes.

2023-03-01 15:33 UTC, molnard commented
Every new round will recreate the denominations. That is the price we need to pay for taproot randomization. However clever things can be done but it is too early to further complicate this with early optimization. 

> slow and therefore unusable when you want to do statistically significant measurements

Give me a code that is slow and I will optimize it.

2023-03-01 15:34 UTC, molnard commented
We need to give out a release candidate on Friday which means we have one day to merge taproot randomization in the master. How can we speed up this?

2023-03-02 07:37 UTC, nopara73 commented
> Every new round will recreate the denominations.

That's good. Then you need to only create the denominations once per round instead of once every user.

> We need to give out a release candidate on Friday

Let's delay that.

> How can we speed up this?

https://calendly.com/nopara73

2023-03-02 08:40 UTC, molnard commented
> Let's delay that.

That is not possible.

2023-03-02 08:51 UTC, molnard commented
> create the denominations once per round instead of once every user

Until I do not see how you are creating statistics from hundreds of rounds it is hard to know. Can you share your method?

2023-03-02 08:54 UTC, molnard commented
> Then you need to only create the denominations once per round instead of once every user.

As far as I can see it is already like that. denominations generated in ctor, like before.

2023-03-02 09:30 UTC, molnard commented
I move all the calculations that can be done in advance.

2023-03-02 09:36 UTC, molnard commented on Sake/Mixer.cs
> +                yield return Decompose(currentUser, filteredDenominations, maxVsizeCredentialValue);
othersInputsParam is not used anymore. Passing in the denominations.

2023-03-02 09:37 UTC, molnard commented on Sake/Mixer.cs
> -            var preFilteredDenoms = DenominationFrequencies
Moved all the calculations as is into GetFilteredDenominations.

2023-03-03 08:31 UTC, nopara73 commented
> Until I do not see how you are creating statistics from hundreds of rounds it is hard to know. Can you share your method?

```cs
for (int i = 0; i < 1_000; i++)
{
   Program.cs
}
```

2023-03-03 08:35 UTC, nopara73 commented
LGTM, even better than the original if I'm not missing something.

2023-03-03 08:35 UTC, merged

2023-03-03 08:40 UTC, nopara73 commented
Actually based on quick measurements it does not make a difference.