Add pre-decompositions
nopara73/Sake pull request #31
Opened 2023-05-26 08:46 UTC by nopara73

2023-05-28 10:03 UTC, yahiheb requested changes

2023-05-28 10:03 UTC, yahiheb commented on Sake/Mixer.cs
> +                    // We can only let this go forward if at least 2 output can be added (denom + potential change)
```suggestion
                    // We can only let this go forward if at least 2 outputs can be added (denom + potential change)
```

2023-05-30 00:23 UTC, turbolay commented
Unrelated to this PR and maybe I'm wrong but I will take the opportunity to raise the concern, this line seems incomplete:
https://github.com/nopara73/Sake/blob/9beb1bf271478b01aeec6a31a8b7c2ec481c0fa9/Sake/Mixer.cs#L365

Shouldn't this condition be
```diff
    if (denom is null || 
+       (remaining != MinAllowedOutputAmount || remainingVsize > denom.ScriptType.EstimateOutputVsize()) &&
        (remaining < MinAllowedOutputAmount + ChangeFee || remainingVsize < denom.ScriptType.EstimateOutputVsize() + ChangeScriptType.EstimateOutputVsize()))
```
Because if the remaining is exactly the `MinAllowedOutputAmount`, one extra output can be added, without worrying about the `ChangeFee` because there won't be any.

2023-05-30 07:52 UTC, nopara73 commented
@turbolay I have spent some minutes trying to understand your comment, but I did not fully grasp it just yet. I suspect you're right. Can you make PRs
- to Sake and to WalletWasabi
- to naive and to pre-decompositions (does Lucas decomposition needs something like this?)
- have a decent description of the PRs
- improve the comments above the code modification

2023-05-30 07:52 UTC, merged

2023-05-31 19:38 UTC, turbolay commented
Something else here: Maybe I don't exactly understand exactly this line:

https://github.com/nopara73/Sake/blob/9beb1bf271478b01aeec6a31a8b7c2ec481c0fa9/Sake/Mixer.cs#L361-L362

But it seems that in the condition L365 that I quoted in my previous message `MinAllowedOutputAmount` should be replaced by `denom.Amount` otherwise, the remaining can be less than 0 if `denom.Aount > MinAllowedOutputAmount + ChangeFee`

2023-06-01 07:21 UTC, nopara73 commented
@turbolay if I have issues comprehending your previous comment, then I'll have issues comprehending the comment that builds on top of that 😄 please make the PRs as I suggested so hopefully it'll be easier to understand what you want by looking at the finished work.

2023-06-01 14:13 UTC, turbolay commented
(it was not built on top of it, it's a different comment that happens to be on the same line)
I will make the PR today.