Verify that sum of inputs is > than min output denom
nopara73/Sake pull request #40
Opened 2023-06-12 16:35 UTC by turbolay

https://github.com/zkSNACKs/WalletWasabi/pull/10842

This PR doesn't add new inputs to the second mix if some groups created are below the economical threshold (option 3 in my [comment](https://github.com/nopara73/Sake/pull/39#issuecomment-1585292732) on the other PR).

2023-06-12 16:37 UTC, turbolay commented on Sake/Mixer.cs
> +                .Where(x => x.EffectiveAmount >= minReasonableOutputAmount)
I had to add this line `.Where(x => x.EffectiveAmount >= minReasonableOutputAmount)` otherwise it was throwing.
@nopara73 either I understood the wrong way and the problem is in another place in my PR either it's a bug on Wasabi's master.

2023-06-13 07:34 UTC, nopara73 commented on Sake/Mixer.cs
> +                .Where(x => x.EffectiveAmount >= minReasonableOutputAmount)
When I remove it, it is not throwing for me. Can you confirm? I tried with fee rates 20, 200, 10_000

2023-06-13 07:50 UTC, turbolay commented on Sake/Mixer.cs
> +                .Where(x => x.EffectiveAmount >= minReasonableOutputAmount)
Try with 100_000.
I also saw some throws for lower amounts, but it's rare.

2023-06-14 07:02 UTC, nopara73 commented on Sake/Mixer.cs
> +                .Where(x => x.EffectiveAmount >= minReasonableOutputAmount)
Alright, something is wrong. First things first. `EffectiveAmount` seems nonsensical to me. Let's discuss killing that and see if we uncover a mystery while doing that: https://github.com/zkSNACKs/WalletWasabi/pull/10890

2023-06-15 08:08 UTC, nopara73 commented on Sake/Mixer.cs
> +                .Where(x => x.EffectiveAmount >= minReasonableOutputAmount)
https://github.com/zkSNACKs/WalletWasabi/pull/10897

2023-06-15 08:10 UTC, nopara73 requested changes
I have one problem left with this PR. The input counts change, which can potentially ruin the result of the simulations. @turbolay can you make sure the input counts remain what they are specified in the `Program.cs`?

2023-06-16 10:43 UTC, turbolay commented
I improved performances.
I ran dotTrace on it, and `CreateChangelessDecompositions` is almost the only function taking time.

2023-06-17 05:56 UTC, turbolay commented
Last commit reverts the changes in `CreateDenominations` and fixes the underlying issue. It mirrors https://github.com/zkSNACKs/WalletWasabi/pull/10902.

2023-06-17 09:09 UTC, closed without merging